import LocalizedStrings from 'react-native-localization';

export const strings = new LocalizedStrings({
    en:{
        start: 'Start working',
        loading: 'Loading...',
        calculating: 'Calculating...',
        exit: 'Exit',
        timeToCharge: 'Time to fool charge: ',
        ru: 'Russian',
        en: 'English',
        titleBattery: 'Battery',
        titleCPU: 'CPU',
        titleMemory: 'Memory',
        titleDevice: 'Device',
        systemInfo: 'System information',
        statistic: 'Statistic',
        averageRAM: 'Average RAM usage: ',
        averageStorage: 'Average storage usage: ',
        averageChargingTime: 'Average charge time: ',
        lastChargeTime: 'Last charge: ',
        locInfo: 'Location info',
        netInfo: 'Network info',
        cpu: 'CPU info',
        ram: 'RAM info',
        deviceMemory: 'Device memory info',
        changeLanguage: 'Change language',
        commonDevInfo: 'Common device info',
        uniqueID: 'Device unique ID: ',
        manufacturer: 'Device manufacturer: ',
        brand: 'Device brand: ',
        model: 'Device model: ',
        deviceName: 'Device name: ',
        userAgent: 'User agent: ',
        deviceID: 'Device ID: ',
        //Location
        deviceLocale: 'Device locale: ',
        deviceCountry: 'Device country: ',
        timeZone: 'Device time zone: ',
        //System inf
        sysName: 'System name: ',
        sysVer: 'System version: ',
        bundleID: 'Bundle ID: ',
        buildNumber: 'Build number: ',
        apiLevel: 'API level: ',
        appInstanceID: 'App instance ID: ',
        phoneNumber: 'Phone number: ',
        serialNumber: 'Serial number: ',
        //Network
        ip: 'IP address: ',
        mac: 'MAC address: ',
        //CPU
        cpuName: 'CPU model: ',
        cpuCount: 'Number of cores: ',
        cpuArch: 'CPU Architecture: ',
        temp: 'CPU temperature: ',
        cpuMin: 'Minimum CPU frequency: ',
        cpuMax: 'Maximum CPU frequency: ',
        cpuCurr: 'Current CPU frequency: ',
        //CPU Usage
        usage: 'CPU usage',
        userProcesses: 'User processes: ',
        sysProcesses: 'System processes: ',
        idle: 'System idle: ',
        other: 'Other: ',
        totalCpu: 'Total CPU usage: ',
        //RAM
        totalRam: 'Total RAM: ',
        freeRam: 'Free RAM: ',
        maxRam: 'Maximum RAM: ',
        //Storage
        storage: 'Storage',
        freeStorage: 'Free device space: ',
        totalStorage: 'Total space on device: ',
        //BatteryInfo
        battery: 'BatteryInfo',
        batteryStatus: 'Status: ',
        batteryState: 'State: ',
    },
    ru: {
        start: 'Начать работу',
        loading: 'Загрузка...',
        timeToCharge: 'Время до полной зарядки: ',
        calculating: 'Идёт подсчёт...',
        exit: 'Выйти',
        ru: 'Русский',
        en: 'Английский',
        titleBattery: 'Батарея',
        titleCPU: 'ЦП',
        titleMemory: 'Память',
        titleDevice: 'Устройство',
        systemInfo: 'Системная информация: ',
        statistic: 'Статистика',
        averageRAM: 'Среднее потребление ОП: ',
        averageStorage: 'Среднее потребление физической памяти: ',
        averageChargingTime: 'Среднее время зарядки: ',
        lastChargeTime: 'Последняя зарядка: ',
        locInfo: 'Информация о местонахождении',
        netInfo: 'Информация о сети: ',
        cpu: 'Центральный процессор',
        ram: 'Оперативная память',
        deviceMemory: 'Память устройства',
        changeLanguage: 'Сменить язык',
        commonDevInfo: 'Общая информация об устройстве',
        uniqueID: 'Уникальный ID устройства: ',
        manufacturer: 'Производитель устройства: ',
        brand: 'Бренд: ',
        deviceID: 'ID устройства: ',
        bundleID: 'ID пакета: ',
        model: 'Модель девайса: ',
        deviceName: 'Имя девайся: ',
        userAgent: 'User agent: ',
        //Location
        deviceLocale: 'Локализация устройства: ',
        deviceCountry: 'Локация устройства: ',
        timeZone: 'Часововй пояс: ',
        //System inf
        sysName: 'Имя ОС: ',
        sysVer: 'Версия ОС: ',
        buildNumber: 'Номер билда: ',
        apiLevel: 'API уровень: ',
        appInstanceID: 'App instance ID: ',
        phoneNumber: 'Номер телефона: ',
        serialNumber: 'Серийный номер: ',
        //Network
        ip: 'IP адрес: ',
        mac: 'MAC адрес: ',
        //CPU
        cpuName: 'Модель ЦП: ',
        cpuCount: 'Количество ядер: ',
        cpuArch: 'Архитектура ЦП: ',
        temp: 'Температура ЦП: ',
        cpuMin: 'Минимальная тактовая частота: ',
        cpuMax: 'Максимальная тактовая частота: ',
        cpuCurr: 'Текущая тактовая частота: ',
        //CPU Usage
        usage: 'Нагрузка на ЦП',
        userProcesses: 'Пользовательские процессы: ',
        sysProcesses: 'Системные процессы: ',
        idle: 'Ожидание системы: ',
        other: 'Другие процессы: ',
        totalCpu: 'Общая нагрузка: ',
        //RAM
        totalRam: 'Всего ОП: ',
        freeRam: 'Свободно ОП: ',
        maxRam: 'Максимум ОП: ',
        //Storage
        storage: 'Накопитель',
        freeStorage: 'Общий объём: ',
        totalStorage: 'Свободно: ',
        //BatteryInfo
        battery: 'Батарея',
        batteryStatus: 'Статус: ',
        batteryState: 'Состояние: ',
    }
});